name: Build NovaFill APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev \
            libjpeg-dev zlib1g-dev \
            libncurses6 libsqlite3-dev libpng-dev \
            libavcodec-dev libavformat-dev libswscale-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libmtdev-dev xclip xsel

      - name: Install buildozer and python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer Cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NovaFill-APK
          path: bin/*.apk
