name: Build NovaFill APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev libsqlite3-dev zlib1g-dev \
                              autoconf automake libtool pkg-config build-essential
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NovaFill-v1.1
          path: bin/*.apk
