name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip build-essential \
              libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libncurses5-dev libtinfo5

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK & Tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
          unzip tools.zip -d cmdline-tools
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-tools/* android-sdk/cmdline-tools/latest/
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NovaFill-APK
          path: bin/*.apk
