name: Build NovaFill APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev libsqlite3-dev zlib1g-dev \
                              autoconf automake libtool pkg-config build-essential git

      - name: Install SDK & Build Tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
          unzip tools.zip -d cmdline-tools
          mv cmdline-tools cmdline-tools-latest
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools-latest android-sdk/cmdline-tools/latest
          yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=android-sdk \
            "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NovaFill-v1.1
          path: bin/*.apk
