name: Build NovaFill APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1 ─ checkout
    - uses: actions/checkout@v4

    # 2 ─ Python 3.10
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3 ─ Linux build dependencies
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential git zip unzip openjdk-17-jdk \
          libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
          libncurses6 libsqlite3-dev libpng-dev \
          libavcodec-dev libavformat-dev libswscale-dev \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libmtdev-dev xclip xsel \
          autoconf automake libtool libtool-bin pkg-config

    # 4 ─ Buildozer + Cython
    - name: Install Buildozer
      run: |
        python -m pip install -U pip
        pip install "buildozer~=1.5" Cython

    # 5 ─ Android SDK & Build-Tools 31 (+legacy sdkmanager alias)
    - name: Install Android SDK & Build-Tools
      run: |
        SDK="$HOME/.buildozer/android/platform/android-sdk"
        mkdir -p "$SDK/cmdline-tools"
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o tools.zip
        unzip -q tools.zip -d "$SDK/cmdline-tools"
        mv "$SDK/cmdline-tools/cmdline-tools" "$SDK/cmdline-tools/latest"

        echo "ANDROID_SDK_ROOT=$SDK"       >> $GITHUB_ENV
        echo "$SDK/platform-tools"         >> $GITHUB_PATH
        echo "$SDK/build-tools/31.0.0"     >> $GITHUB_PATH

        yes | "$SDK/cmdline-tools/latest/bin/sdkmanager" \
              --sdk_root="$SDK" \
              "platform-tools" "platforms;android-31" "build-tools;31.0.0"

        # ⇢ Buildozer still expects $SDK/tools/bin/sdkmanager
        mkdir -p "$SDK/tools/bin"
        ln -sf "$SDK/cmdline-tools/latest/bin/sdkmanager" "$SDK/tools/bin/sdkmanager"

    # 6 ─ clean stale platform cache (optional)
    - name: Zap stale .buildozer platform dir
      run: rm -rf .buildozer/android/platform

    # 7 ─ build APK
    - name: Build APK with Buildozer
      run: |
        export CFLAGS="-Wno-error=deprecated-declarations"
        export CXXFLAGS="-Wno-error=deprecated-declarations"
        export REPORTLAB_NO_C_EXTENSION=1
        buildozer android debug

    # 8 ─ upload artefact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: NovaFill-APK
        path: bin/*.apk
