name: Build NovaFill APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1  checkout
    - uses: actions/checkout@v4

    # 2  Python 3.10
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3  Linux build dependencies
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential git zip unzip openjdk-17-jdk \
          libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
          libncurses6 libsqlite3-dev libpng-dev \
          libavcodec-dev libavformat-dev libswscale-dev \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libmtdev-dev xclip xsel \
          autoconf automake libtool libtool-bin pkg-config

    # 4  Buildozer + Cython
    - name: Install Buildozer
      run: |
        python -m pip install -U pip
        pip install "buildozer~=1.5" Cython

    # 5  Android SDK / build-tools 31
    - name: Install Android SDK & Build-Tools
      run: |
        SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
        mkdir -p "$SDK_ROOT/cmdline-tools"
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o tools.zip
        unzip -q tools.zip -d "$SDK_ROOT/cmdline-tools"
        mv "$SDK_ROOT/cmdline-tools/cmdline-tools" "$SDK_ROOT/cmdline-tools/latest"

        echo "ANDROID_SDK_ROOT=$SDK_ROOT" >> $GITHUB_ENV
        echo "$SDK_ROOT/platform-tools"     >> $GITHUB_PATH
        echo "$SDK_ROOT/build-tools/31.0.0" >> $GITHUB_PATH

        yes | "$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
               --sdk_root="$SDK_ROOT" \
               "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    # 6  (optional) keep the cache clean between runs
    - name: Zap stale .buildozer platform dir
      run: rm -rf .buildozer/android/platform

    # 7  ⚡ build APK
    - name: Build APK with Buildozer
      run: |
        # ① deprecation warnings → warnings
        export CFLAGS="-Wno-error=deprecated-declarations"
        export CXXFLAGS="-Wno-error=deprecated-declarations"
        # ② tell ReportLab to *skip* its native _rl_accel
        export REPORTLAB_NO_C_EXTENSION=1
        buildozer android debug

    # 8  upload result
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: NovaFill-APK
        path: bin/*.apk
